on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress  --prefer-dist

      - name: Install Dependencies
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate App Key
        run: php artisan key:generate

      - name: Config Clearing
        run: php artisan config:clear

      - name: Cache Clearing
        run: php artisan cache:clear

      - name: Route Clearing
        run: php artisan route:clear

        
      - name: Route Clearing
        run: php artisan optimize:clear

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.megascrypto.com
          username: u674741462.demenhost
          password: Onyedika90
          server-dir: /tron/
